import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

type Props = {
  results: any[]
}

const Home: NextPage<Props> = ({results}) => {

  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre as string;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }?api_key=8a72281fad7754ffadb67926e404b457`
  ).then(res => res.json());

  return {
    props: {
      results: request.results
    },
  };
};

export default Home;
